### ISSUE TITLE
How to run the plugin on a horizontal scrolling site?

### ISSUE THREAD

**Issue by DailyciousInfo** [jeremenichelli/scrollProgress#1]
Hi..

First of all, thanks you for this plugin.. it's great.
In my new web project, I would like to implement this plugin for a horizontal scroll. Is this possible ?

Thank you

**Comment by jeremenichelli** [comment]
Hi,

The horizontal version of this library is planned for the next version, though I'm not sure when it will be released since I need to do some heavy testing around it and decided how configuration will be handle.

Definitely on the TODO list.

**Comment by DailyciousInfo** [comment]
Thank you !

Good to know. Good luck !

**Comment by jeremenichelli** [comment]
@DailyciousInfo the last version has support for horizontal scolling in case you are still interested.
