### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by finseth** [jeremenichelli/scrollProgress#2]
Hi,

Thanks for making this script 👍 
Unfortunately I can't get it to run because of the following error:

Uncaught TypeError: Cannot read property 'appendChild' of null
    at _createElements (scrollprogress.js:48)
    at Object._set [as set] (scrollprogress.js:107)
    at main.js:1

Would really appreciate it if you could look into it or let me know if I'm doing something wrong :) Installed via npm if that helps..

Cheers

**Comment by jeremenichelli** [comment]
Hi @finseth, can you create a small repo with an example of what you're trying to accomplish? It's hard to tell what's wrong from your description.

**Comment by LasaleFamine** [comment]
Hello there! 
Here just to say I'm getting the same error.

I'm trying to implement the scroll progress bar within an element of my Polymer 1.x (Shady DOM) application, but I'm getting this error. 
Just noticed the issue, I will try to indagate better, hope it helps!

UPDATE (I have debugged): I'm importing the library with `webpack` and `es6` `import` and I noticed that when `scrollProgress` is instantiated the `document.body` is `null`. So the `appendChild` on the `body` will not work when the `set()` method is called.

**Comment by jeremenichelli** [comment]
I can imagine this happening when implementing this within any component based library since there's no way to remove the listener currently. This library needs an update to allow a low level api to be accessed.

**Comment by jeremenichelli** [comment]
About the body being null. My only guess is that you have to make sure the DOM is ready when your bundle runs. Unless webpack is modifying the window and coument globals which would be super weird.

**Comment by jeremenichelli** [comment]
@LasaleFamine closing this issue since the library has drastically changed on this last version. Let me know if you experience the same issue with it.
